version: 2

# Sphinx configuration key to ensure Sphinx is properly set up
sphinx:
  configuration: conf.py  # This tells Read the Docs to use the conf.py file

# Build environment settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
